<a href="https://colab.research.google.com/github/pravin7353/Machinelearning/blob/main/k_nearest_neighbour_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np 
import pandas as pd

In [6]:
df = pd.read_csv(r'/content/drive/MyDrive/bangalore_house.csv')

In [7]:
df

      bath  balcony  ...  location_Mahadevpura  location_Tumkur Road
0      3.0      2.0  ...                     0                     0
1      3.0      3.0  ...                     0                     0
2      3.0      2.0  ...                     0                     0
3      2.0      2.0  ...                     0                     0
4      2.0      2.0  ...                     0                     0
...    ...      ...  ...                   ...                   ...
7115   3.0      2.0  ...                     0                     0
7116   3.0      1.0  ...                     0                     0
7117   2.0      1.0  ...                     0                     0
7118   2.0      1.0  ...                     0                     0
7119   2.0      1.0  ...                     0                     0

[7120 rows x 108 columns]

In [25]:
X = df.drop('price', axis=1)
y = df['price']

In [30]:
from sklearn.model_selection import train_test_split

In [31]:
X_train, X_test, y_train, y_test = train_test_split(X, y , test_size=0.2, random_state=42)

In [32]:
from sklearn.neighbors import KNeighborsRegressor

In [33]:
knr = KNeighborsRegressor(n_neighbors=5)

In [34]:
knr.fit(X_train, y_train)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
                    metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                    weights='uniform')

In [35]:
knr.score(X_test, y_test)

0.9766747439831145

In [50]:
knr1 = knr.predict(X_test)
pd.DataFrame([knr1])

    0     1     2      3      4     ...    1419   1420   1421  1422   1423
0  46.98  59.4  65.0  313.8  59.25  ...  48.432  206.6  56.76  26.2  49.22

[1 rows x 1424 columns]

In [47]:
pd.DataFrame([y_test])

       960   132   2431   2229  4503  ...  4970   553   1397  4056  1817
price  47.0  60.0  65.0  325.0  60.0  ...  48.0  205.0  56.5  26.0  49.0

[1 rows x 1424 columns]